# openapi2-run.yaml
swagger: '2.0'
info:
  title: CRC-API
  description:  API Gateway
  version: 1.0.0
host: visitorcounter-v2jitaeb3q-uc.a.run.app

schemes:
- https
produces:
- application/json
paths:
  /viewcount:
    post:
      summary: Cloudrun view count
      operationId: viewcount
      x-google-backend:
        address: https://visitorcounter-v2jitaeb3q-uc.a.run.app
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      description: "Cors associated request"
      operationId: corsRequest
      x-google-backend:
        address: https://visitorcounter-v2jitaeb3q-uc.a.run.app
      responses:
        '200':
          description: "Allow"
        '401':
          description: "Cors not allowed"
  